insert into pointsymbol(ID,NAME) values(1,'文化、媒体');
insert into pointsymbol(ID,NAME, FATHERID) values(2,'风景名胜',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(3,'风景名胜',2,'0x9080','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(4,'科技馆',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(5,'科技馆',4,'0x9500','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(6,'报社、出版社、杂志社',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(7,'报社、出版社、杂志社',6,'0x9600','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(8,'寺庙、道观',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(9,'寺庙、道观',8,'0x9180','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(10,'电台、电视台、电影制片厂',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(11,'电台、电视台、电影制片厂',10,'0x9700','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(12,'博物馆、纪念馆、展览馆、陈列馆',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(13,'博物馆、纪念馆、展览馆、陈列馆',12,'0x9380','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(14,'陵园、公墓',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(15,'陵园、公墓',14,'0x9800','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(16,'文化馆、活动中心',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(17,'文化馆、活动中心',16,'0x9480','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(18,'教堂',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(19,'教堂',18,'0x9200','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(20,'基督教',18,'0x9202','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(21,'天主教',18,'0x9201','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(22,'伊斯兰教',18,'0x9203','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(23,'资料馆、档案馆',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(24,'资料馆、档案馆',23,'0x9400','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(25,'美术馆',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(26,'美术馆',25,'0x9300','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(27,'文工团、歌舞团  、艺术团',1);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(28,'文工团、歌舞团  、艺术团',27,'0x9580','point.png');
insert into pointsymbol(ID,NAME) values(29,'其它');
insert into pointsymbol(ID,NAME, FATHERID) values(30,'照相、影楼、彩扩',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(31,'照相、影楼、彩扩',30,'0xa600','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(32,'社会团体',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(33,'社会团体',32,'0xa200','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(34,'美容院、理发店、按摩、SPA',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(35,'美容院、理发店、按摩、SPA',34,'0xa080','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(36,'保险',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(37,'新华人寿保险',36,'0xaa81','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(38,'中国人寿保险',36,'0xaa82','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(39,'保险',36,'0xaa80','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(40,'中国太平洋保险',36,'0xaa83','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(41,'电力营业厅',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(42,'电力营业厅',41,'0xa300','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(43,'科研机构',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(44,'科研机构',43,'0xa880','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(45,'洗衣店/干洗店',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(46,'洗衣店/干洗店',45,'0xa280','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(47,'邮局',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(48,'邮局',47,'0xa380','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(49,'旅行社',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(50,'旅行社',49,'0xa480','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(51,'银行',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(52,'兴业银行',51,'0xa18f','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(53,'光大银行',51,'0xa189','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(54,'工商银行',51,'0xa181','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(55,'民生银行',51,'0xa188','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(56,'广东发展银行',51,'0xa18d','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(57,'中信银行',51,'0xa187','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(58,'银行',51,'0xa180','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(59,'邮政储蓄',51,'0xa18b','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(60,'招商银行',51,'0xa186','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(61,'深圳发展银行',51,'0xa18e','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(62,'ATM/自助银行',51,'0xa199','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(63,'农村信用社/农村商业银行',51,'0xa191','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(64,'城市信用社',51,'0xa192','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(65,'华夏银行',51,'0xa18a','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(66,'商业银行',51,'0xa18c','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(67,'建设银行',51,'0xa182','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(68,'浦东发展银行',51,'0xa190','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(69,'交通银行',51,'0xa185','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(70,'农业银行',51,'0xa183','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(71,'中国银行',51,'0xa184','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(72,'洗浴中心、足浴',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(73,'洗浴中心、足浴',72,'0xa100','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(74,'物流、快运',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(75,'物流、快运',74,'0xa400','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(76,'教育',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(77,'其他教育机构',76,'0xa709','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(78,'中学',76,'0xa703','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(79,'小学',76,'0xa702','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(80,'大专院校',76,'0xa700','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(81,'幼儿园/托儿所',76,'0xa701','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(82,'中专/职高/技校',76,'0xa708','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(83,'驾校',76,'0xa706','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(84,'小区',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(85,'小区',84,'0xa900','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(86,'公司企业',29);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(87,'证券公司/营业部',86,'0xa983','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(88,'公司',86,'0xa980','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(89,'厂矿企业',86,'0xa982','point.png');
insert into pointsymbol(ID,NAME) values(90,'交通');
insert into pointsymbol(ID,NAME, FATHERID) values(91,'港口、码头',90);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(92,'港口、码头',91,'0x8180','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(93,'高速服务区、停车区',90);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(94,'高速服务区、停车区',93,'0x8380','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(95,'收费站',90);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(96,'收费站',95,'0x8400','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(97,'机场',90);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(98,'机场',97,'0x8100','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(99,'高速出入口',90);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(100,'高速出入口',99,'0x8300','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(101,'车站',90);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(102,'轻轨站/磁悬浮',101,'0x8084','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(103,'地铁站',101,'0x8082','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(104,'火车站',101,'0x8081','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(105,'长途客运站',101,'0x8083','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(106,'车站',101,'0x8080','point.png');
insert into pointsymbol(ID,NAME) values(107,'零售业');
insert into pointsymbol(ID,NAME, FATHERID) values(108,'溜冰场',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(109,'溜冰场',108,'0x6b00','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(110,'烟酒副食、地方特产',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(111,'烟酒副食、地方特产',110,'0x2280','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(112,'超市',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(113,'超市',112,'0x2100','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(114,'北京华联',112,'0x2101','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(115,'红旗超市',112,'0x2127','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(116,'联华/世纪联华',112,'0x2102','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(117,'家乐福',112,'0x2106','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(118,'普尔斯马特',112,'0x2105','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(119,'华润',112,'0x2111','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(120,'华联/上海华联',112,'0x2125','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(121,'沃尔玛',112,'0x2116','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(122,'家得利',112,'0x2117','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(123,'苏果超市',112,'0x2122','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(124,'农工商超市',112,'0x2120','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(125,'互惠超市',112,'0x2126','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(126,'好又多',112,'0x2128','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(127,'中百超市',112,'0x2123','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(128,'津工超市',112,'0x2118','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(129,'物美',112,'0x2124','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(130,'民润超市',112,'0x2119','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(131,'赛马场',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(132,'赛马场',131,'0x6400','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(133,'垂钓',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(134,'垂钓',133,'0x6f00','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(135,'百货商城、百货商店',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(136,'百货商城、百货商店',135,'0x2200','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(137,'游乐园',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(138,'游乐园',137,'0x6300','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(139,'小商品城',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(140,'小商品城',139,'0x2180','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(141,'便利店',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(142,'迪亚天天便利店',141,'0x2090','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(143,'捷强便利店',141,'0x2091','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(144,'便利店',141,'0x2080','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(145,'光明便利店',141,'0x2088','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(146,'良友金伴便利店',141,'0x2085','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(147,'可的便利店',141,'0x2083','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(148,'711便利店',141,'0x2082','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(149,'喜事多便利店',141,'0x2089','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(150,'罗森便利店',141,'0x2087','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(151,'好德便利店',141,'0x2084','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(152,'21世纪便利店',141,'0x2081','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(153,'快客便利店',141,'0x2086','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(154,'夜总会、歌舞厅、迪厅',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(155,'夜总会、歌舞厅、迪厅',154,'0x6c00','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(156,'电影院',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(157,'电影院',156,'0x6500','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(158,'健身房、康乐宫、舍宾',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(159,'健身房、康乐宫、舍宾',158,'0x6d00','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(160,'体育场馆',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(161,'体育场馆',160,'0x6600','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(162,'天然浴场',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(163,'天然浴场',162,'0x6380','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(164,'剧场、戏院、音乐厅',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(165,'剧场、戏院、音乐厅',164,'0x6580','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(166,'电器商场',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(167,'国美',166,'0x2301','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(168,'电器商场',166,'0x2300','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(169,'练歌房、KTV',107);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(170,'练歌房、KTV',169,'0x6680','point.png');
insert into pointsymbol(ID,NAME) values(171,'公共设施');
insert into pointsymbol(ID,NAME, FATHERID) values(172,'图书馆',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(173,'图书馆',172,'0x7180','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(174,'公共厕所',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(175,'公共厕所',174,'0x7880','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(176,'火葬场、殡仪馆',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(177,'火葬场、殡仪馆',176,'0x7800','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(178,'政府机关',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(179,'政府机关',178,'0x7080','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(180,'会议中心、展览中心',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(181,'会议中心、展览中心',180,'0x7400','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(182,'宠物医院',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(183,'宠物医院',182,'0x7580','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(184,'社区医疗',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(185,'社区医疗',184,'0x7280','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(186,'事务所',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(187,'事务所',186,'0x7680','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(188,'广场',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(189,'广场',188,'0x7380','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(190,'培训中心',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(191,'培训中心',190,'0x7480','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(192,'公安机关',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(193,'交警队',192,'0x7103','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(194,'公安机关',192,'0x7100','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(195,'派出所',192,'0x7102','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(196,'公安局',192,'0x7101','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(197,'防疫站',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(198,'防疫站',197,'0x7500','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(199,'医院',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(200,'医院',199,'0x7200','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(201,'福利院、敬老院',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(202,'福利院、敬老院',201,'0x7700','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(203,'人才市场',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(204,'人才市场',203,'0x7600','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(205,'公园',171);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(206,'公园',205,'0x7300','point.png');
insert into pointsymbol(ID,NAME) values(207,'餐饮');
insert into pointsymbol(ID,NAME, FATHERID) values(208,'酒吧',207);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(209,'酒吧',208,'0x1500','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(210,'地方风味与名店',207);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(211,'地方风味与名店',210,'0x1980','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(212,'中餐馆',207);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(213,'中餐馆',212,'0x1380','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(214,'异国风味',207);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(215,'异国风味',214,'0x1300','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(216,'茶楼，咖啡店',207);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(217,'茶楼，咖啡店',216,'0x1600','point.png');
insert into pointsymbol(ID,NAME, FATHERID) values(218,'快餐',207);
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(219,'马兰拉面',218,'0x1081','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(220,'赛百味',218,'0x10c8','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(221,'达美乐',218,'0x10c7','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(222,'永和大王',218,'0x1085','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(223,'麦当劳',218,'0x10c0','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(224,'必胜客',218,'0x10c2','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(225,'肯德基',218,'0x10c1','point.png');
insert into pointsymbol(ID,NAME, FATHERID, POINTCODE,IMAGE) values(226,'快餐',218,'0x1080','point.png');
